ALTER TABLE day_log ADD COLUMN streak_day BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE day_log ADD COLUMN timer_honored BOOLEAN NOT NULL DEFAULT 1;
ALTER TABLE day_log ADD COLUMN grace_used BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE day_log ADD COLUMN current_streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE day_log ADD COLUMN longest_streak INTEGER NOT NULL DEFAULT 0
